import type { CourseCard } from './types';

export const COURSES: CourseCard[] = [
  // --- Statistical domain ---
  {
    id: 'c01',
    title: 'Foundations of Official Statistics',
    provider: 'iGOT Karmayogi',
    domain: 'statistical',
    level: 'Foundation',
    durationHours: 8,
    description:
      'Principles of official statistics, NSS design, sampling frames and the statistical production lifecycle.',
    skills: ['Sampling design', 'Data quality', 'NSS / NFHS'],
    url: 'https://igotkarmayogi.gov.in',
    roles: ['SSO', 'JSO', 'ISS Officer'],
  },
  {
    id: 'c02',
    title: 'National Accounts & GDP Compilation',
    provider: 'NSSTA',
    domain: 'statistical',
    level: 'Advanced',
    durationHours: 16,
    description:
      'Supply-use tables, GDP compilation and quarterly indicator methodology used by MoSPI.',
    skills: ['National accounts', 'Supply-use tables', 'GDP estimation'],
    url: 'https://nssta.gov.in',
    roles: ['JSO', 'ISS Officer'],
  },
  {
    id: 'c10',
    title: 'Statistical Quality Assurance Framework',
    provider: 'NSSTA',
    domain: 'statistical',
    level: 'Intermediate',
    durationHours: 8,
    description:
      'MoSPI SQAF, quality dimensions, peer review and process documentation standards.',
    skills: ['SQAF', 'Quality assurance', 'Process docs'],
    url: 'https://nssta.gov.in',
    roles: ['JSO', 'ISS Officer'],
  },
  // --- Technical domain (statistical computing) ---
  {
    id: 'c03',
    title: 'R for Statistical Analysis',
    provider: 'iGOT Karmayogi',
    domain: 'technical',
    level: 'Intermediate',
    durationHours: 12,
    description:
      'Tidyverse workflows, survey-weighted estimation and reproducible RMarkdown reporting.',
    skills: ['R', 'tidyverse', 'survey weights'],
    url: 'https://igotkarmayogi.gov.in',
    roles: ['SSO', 'JSO', 'AI/ML Engineer', 'GIS Specialist'],
  },
  {
    id: 'c05',
    title: 'GIS & Spatial Data for Administrators',
    provider: 'iGOT Karmayogi',
    domain: 'technical',
    level: 'Intermediate',
    durationHours: 10,
    description:
      'QGIS basics, geocoding census data and choropleth mapping for district-level indicators.',
    skills: ['QGIS', 'Geocoding', 'Spatial analysis'],
    url: 'https://igotkarmayogi.gov.in',
    roles: ['SSO', 'JSO', 'GIS Specialist'],
  },
  // --- Technical domain (engineering) ---
  {
    id: 'c11',
    title: 'Python for Engineering & Data',
    provider: 'NSSTA',
    domain: 'technical',
    level: 'Intermediate',
    durationHours: 14,
    description:
      'Python fundamentals, OOP, testing and Pandas for building robust statistical applications.',
    skills: ['Python', 'OOP', 'Testing', 'Pandas'],
    url: 'https://nssta.gov.in',
    roles: ['Software Engineer', 'Full Stack Developer', 'AI/ML Engineer', 'Data Engineer', 'GIS Specialist'],
  },
  {
    id: 'c12',
    title: 'System Architecture for Government Platforms',
    provider: 'iGOT Karmayogi',
    domain: 'technical',
    level: 'Advanced',
    durationHours: 12,
    description:
      'Scalable architecture patterns, microservices, API design and high-availability for e-Gov systems.',
    skills: ['System architecture', 'Microservices', 'API design', 'Scalability'],
    url: 'https://igotkarmayogi.gov.in',
    roles: ['Software Engineer', 'Full Stack Developer', 'Cloud & DevOps Engineer'],
  },
  {
    id: 'c13',
    title: 'Full-Stack Web Development with React & Node',
    provider: 'NSSTA',
    domain: 'technical',
    level: 'Intermediate',
    durationHours: 18,
    description:
      'Building responsive data portals with React, REST/GraphQL APIs and PostgreSQL backends.',
    skills: ['React', 'Node.js', 'REST APIs', 'PostgreSQL'],
    url: 'https://nssta.gov.in',
    roles: ['Full Stack Developer', 'Software Engineer'],
  },
  {
    id: 'c14',
    title: 'AI/ML for Official Statistics',
    provider: 'NSSTA',
    domain: 'technical',
    level: 'Advanced',
    durationHours: 20,
    description:
      'Nowcasting, imputation, time-series forecasting and model deployment for statistical indicators.',
    skills: ['PyTorch', 'Forecasting', 'Model deployment', 'MLOps'],
    url: 'https://nssta.gov.in',
    roles: ['AI/ML Engineer', 'Data Engineer'],
  },
  {
    id: 'c15',
    title: 'Data Engineering & Pipeline Orchestration',
    provider: 'iGOT Karmayogi',
    domain: 'technical',
    level: 'Advanced',
    durationHours: 16,
    description:
      'ETL/ELT pipelines, Airflow orchestration, Spark at scale and data warehousing for bureaus.',
    skills: ['ETL', 'Airflow', 'Spark', 'Data warehousing'],
    url: 'https://igotkarmayogi.gov.in',
    roles: ['Data Engineer', 'AI/ML Engineer', 'Software Engineer'],
  },
  {
    id: 'c16',
    title: 'Cloud Infrastructure & DevOps on AWS',
    provider: 'iGOT Karmayogi',
    domain: 'technical',
    level: 'Advanced',
    durationHours: 15,
    description:
      'Kubernetes, Terraform IaC, CI/CD pipelines, monitoring and cost governance on cloud.',
    skills: ['AWS', 'Kubernetes', 'Terraform', 'CI/CD', 'Monitoring'],
    url: 'https://igotkarmayogi.gov.in',
    roles: ['Cloud & DevOps Engineer', 'Software Engineer', 'Full Stack Developer'],
  },
  {
    id: 'c17',
    title: 'API Design & Integration with API Setu',
    provider: 'NSSTA',
    domain: 'technical',
    level: 'Intermediate',
    durationHours: 8,
    description:
      'Designing REST APIs, OAuth2 authentication and publishing services on India\u2019s API Setu.',
    skills: ['REST APIs', 'OAuth2', 'API Setu', 'Integration'],
    url: 'https://nssta.gov.in',
    roles: ['Software Engineer', 'Full Stack Developer', 'Data Engineer'],
  },
  {
    id: 'c18',
    title: 'PostGIS & Spatial Database Engineering',
    provider: 'NSSTA',
    domain: 'technical',
    level: 'Advanced',
    durationHours: 10,
    description:
      'Spatial indexing, PostGIS queries, raster analysis and building geospatial APIs.',
    skills: ['PostGIS', 'Spatial indexing', 'Geocoding', 'Python'],
    url: 'https://nssta.gov.in',
    roles: ['GIS Specialist', 'Software Engineer', 'Data Engineer'],
  },
  // --- Digital governance ---
  {
    id: 'c06',
    title: 'Data-Driven e-Governance',
    provider: 'iGOT Karmayogi',
    domain: 'digital_governance',
    level: 'Foundation',
    durationHours: 6,
    description:
      'India Stack, API Setu, data portals and citizen-centric digital service delivery.',
    skills: ['India Stack', 'API Setu', 'Open data'],
    url: 'https://igotkarmayogi.gov.in',
    roles: ['SSO', 'JSO', 'ISS Officer', 'Software Engineer', 'Full Stack Developer', 'Cloud & DevOps Engineer'],
  },
  {
    id: 'c07',
    title: 'Building National Data Portals',
    provider: 'NSSTA',
    domain: 'digital_governance',
    level: 'Advanced',
    durationHours: 12,
    description:
      'Designing scalable open-data portals, metadata standards (DDI / SDMX) and CKAN deployment.',
    skills: ['CKAN', 'SDMX', 'DDI', 'Open data portals'],
    url: 'https://nssta.gov.in',
    roles: ['JSO', 'ISS Officer', 'Full Stack Developer', 'Data Engineer'],
  },
  // --- Behavioural ---
  {
    id: 'c08',
    title: 'Leadership in Public Statistics',
    provider: 'iGOT Karmayogi',
    domain: 'behavioural',
    level: 'Advanced',
    durationHours: 9,
    description:
      'Strategic leadership, inter-departmental coordination and statistical diplomacy.',
    skills: ['Leadership', 'Coordination', 'Strategy'],
    url: 'https://igotkarmayogi.gov.in',
    roles: ['ISS Officer'],
  },
  {
    id: 'c09',
    title: 'Ethics & Communication of Statistics',
    provider: 'NSSTA',
    domain: 'behavioural',
    level: 'Foundation',
    durationHours: 5,
    description:
      'UN Fundamental Principles, data dissemination ethics and media communication of indicators.',
    skills: ['Ethics', 'Communication', 'UN FPC'],
    url: 'https://nssta.gov.in',
    roles: ['SSO', 'JSO', 'ISS Officer', 'AI/ML Engineer', 'Software Engineer'],
  },
];
